# Generated by Django 5.2 on 2025-05-11 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourList', '0004_alter_tour_view_count'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='tour',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='TourList.tour'),
            preserve_default=False,
        ),
    ]
