# Generated by Django 5.2 on 2025-05-11 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='tour',
        ),
    ]
