# Generated by Django 5.2 on 2025-05-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('content', models.TextField()),
                ('short_annotation', models.CharField(max_length=100)),
                ('date_add', models.DateTimeField(auto_now_add=True)),
                ('date_edit', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(max_length=32)),
                ('image', models.ImageField(upload_to='Tour/static/img')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
    ]
