# Generated by Django 5.2 on 2025-05-03 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourList', '0002_alter_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='view_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
