# Generated by Django 5.2 on 2025-05-10 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_created_at_alter_cart_user_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking_date',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
