# Generated by Django 5.2 on 2025-05-10 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TourList', '0004_alter_tour_view_count'),
        ('cart', '0003_order_booking_date_order_email_order_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_details', to='cart.order')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TourList.tour')),
            ],
        ),
    ]
